import Head from "next/head";
import styles from "../styles/Home.module.css";
import Ants from "../components/Ants";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ant App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Ants />
      </main>
    </div>
  );
}
